In [9]:
import numpy as np
import matplotlib.pyplot as plt
x1=[[1,1,1,1]]
x2=[[1,-1,-1,1]]
x3=[[-1,1,-1,-1]]
x4=[[1,-1,-1,-1]]

x11 = np.transpose(x1 , axes=None)
print(x11)
w1=x1*x11
print(w1)

x21 = np.transpose(x2 , axes=None)
print(x21)
w2=x2*x21
print(w2)

x31 = np.transpose(x3 , axes=None)
print(x31)
w3=x3*x31
print(w3)

x41 = np.transpose(x4 , axes=None)
print(x41)
w4=x4*x41
print(w4)


[[1]
 [1]
 [1]
 [1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[ 1]
 [-1]
 [-1]
 [ 1]]
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [-1  1  1 -1]
 [ 1 -1 -1  1]]
[[-1]
 [ 1]
 [-1]
 [-1]]
[[ 1 -1  1  1]
 [-1  1 -1 -1]
 [ 1 -1  1  1]
 [ 1 -1  1  1]]
[[ 1]
 [-1]
 [-1]
 [-1]]
[[ 1 -1 -1 -1]
 [-1  1  1  1]
 [-1  1  1  1]
 [-1  1  1  1]]


In [10]:
W = w1+w2+w3+w4
print(W)


[[ 4 -2  0  2]
 [-2  4  2  0]
 [ 0  2  4  2]
 [ 2  0  2  4]]


In [11]:
np.dot(x1,W)

array([[4, 4, 8, 8]])

In [15]:
def make_diagonal_zero(matrix):
    for i in range(min(len(matrix),len(matrix[0]))):
        matrix[i][i]=0
    return matrix

In [16]:
Wd = make_diagonal_zero(W)
print(Wd)

[[ 0 -2  0  2]
 [-2  0  2  0]
 [ 0  2  0  2]
 [ 2  0  2  0]]


In [17]:
xd = np.dot(x1,Wd)

In [18]:
def activate(x,theta=0):
    return np.where(x>theta, 1 , np.where(x==theta , x, -1))
x_act = activate(xd)
print(x_act)

[[0 0 1 1]]


In [19]:
if np.array_equal(x1,x_act):
    print("Testing Incomplete")
else:
    print("Testing Failed")

Testing Failed
